version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    # dev
#    command: python manage.py runserver 0.0.0.0:8000
    # prod
    command: gunicorn school.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
#    volumes:
#      - .:/usr/src/app/
#    ports:
#      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  vue:
    build:
      context: ./scool-ui
      dockerfile: Dockerfile
    volumes:
      - vue_dist:/app/dist
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - vue_dist:/app/dist
    depends_on:
      - web
      - vue

volumes:
  postgres_data:
  static_volume:
  media_volume:
  vue_dist: